version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: udyam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d udyam"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/udyam
      SCHEMA_PATH: ./scraping/schema.json
    volumes:
      - ./scraping:/app/scraping:ro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  
